
cli_flags = [
    ["-g", "Run all image tests."],
]

watch_dirs = [

]

watch_files = [
    "/ptest/pimage/main.cc",
    "/ptest/ptest.cc",
    "/ptest/ptest.hh",
    "/src/lib/process.hh",
    "/src/lib/fs.cc",
    "/src/image/bmp.cc",
    "/src/image/bmp.hh",
]

include_dirs = [
    "/ptest",
    "/src",
    "/src/lib",
    "/src/image",
]

source_files = [
    "/ptest/ptest.cc", 
    "/src/lib/process.hh", 
    "/src/lib/result.cc", 
    "/src/lib/string.cc", 
    "/src/lib/fs.cc", 
    "/src/image/bmp.cc"
]


main = "/ptest/pimage/main.cc"