
#ifndef DRAW_HH
#define DRAW_HH

#include <string>
#include <vector>

#include "math/vecmat.hh"

#include "Windowing.hpp"

#include "conductor_viewport.hh"

#include "render/bitmap.hh"

namespace draw {


typedef struct Box2df_draw {
    f2 pos;
    f2 size;
} Box2df_draw;


/** Draw information for transforming texture into main_view */
typedef struct TransformContext {
    float zoom = 1.0f;
    f2 pan_texture_pos;         /** Scene origin pos, measured from main_view origin, in scene units. Nightmare! */
    f2 cursor_pos_main_view;    /** Cursor position in main view, in scene units - exact pixels */
    f2 cursor_pos_scene;        /** cursor location relative to scene/texture origin - exact */
    i2 cursor_pos_scene_px;     /** cursor location relative to origin - rounded down to pixel */
} TransformContext;


typedef struct Brush {
    int size = 2;
    BitmapPixel color = pixel_color_green;
} Brush;


/** Draw information for transforming texture into main_view */
typedef struct DrawState {
    /** Is set if canvas panning is currently enabled, usually when middle mouse button is held down */
    bool pan_canvas = false;
    /** Flag that is set if currently drawing. Usually enabled when left mouse button held down triggering bitmap draw call on mouse movement. */
    bool drawing = false;
} DrawState;


void init(const ViewportContext& viewport_context);

void update_window(const ViewportContext& viewport_context);

void set_cursor_main_view(ViewportCursor cursor_main_view);

/** Returns true if cursor is grabbed */
bool left_btn_down();
void left_btn_up();
void mouse_backward();
void mouse_forward();
/** Returns true if cursor is grabbed */
bool middle_btn_down();
void middle_btn_up();
void scroll(double dy);
void cursor_move(ViewportCursor cursor_delta);

void draw();

TransformContext& ui_get_transform_context();
Brush& ui_get_brush();



typedef struct PixelTransaction {
    int x;
    int y;
    BitmapPixel pixel_from;
    BitmapPixel pixel_to;

    PixelTransaction(int _x, int _y, BitmapPixel _pixel_from, BitmapPixel _pixel_to) 
        :   x{_x}, 
            y{_y}, 
            pixel_from{_pixel_from}, 
            pixel_to{_pixel_to} {};
} PixelTransaction;

typedef std::vector<PixelTransaction> BitmapTransaction;

/** A bitmap that automatically reloads a bound glTexture when updated. */
typedef struct BitmapTexture_Dynamic {
    std::string id;

    /** Bitmap generated by the currently pointed to transaction. Get updated on every transaction. */
    ::Bitmap bitmap_current_state;
    /** Bitmap that is transfered and rendered on every draw call. */
    ::Bitmap bitmap_rendered;

    /** Always points to the bitmap-transaction the took you to current bitmap state. */
    int index_last_bitmap_transaction = -1;
    /** A list of all bitmap change transactions. */
    std::vector<BitmapTransaction> bitmap_transactions;
    /** Records a new transaction, and update the previous bitmap to match the currently rendered one. Removes any available redos. */
    void transaction_new();
    /** Update both bitmaps to match the bitmap from which the current one was generated. */
    void transaction_undo();
    /** Update both bitmaps to match the bitmap using the next transaction. */
    void transaction_redo();
    
    /** Bitmap storage in VRAM as texture */
    uint texture;

    /**  */
    Box2df_draw box;

    void draw(int x, int y);


    /** Reload the texture with current bitmap data. */
    void reload_texture();

    /** Set the 4x4 transformation matrix that will be set as shader uniform */
    void updateTransformationMatrix();

    float squareTransform[16] = {   1, 0, 0, 0,
                                    0, 1, 0, 0,
                                    0, 0, 1, 0,
                                    0, 0, 0, 1, };

    BitmapTexture_Dynamic(uint width, uint height);
} BitmapTexture_Dynamic;



}

#endif 